<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>WutongApiTestReport</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">WutongApiTestReport</h1>
<p class='attribute'><strong>测试人员 : </strong> ZhouNuo</p>
<p class='attribute'><strong>开始时间 : </strong> 2018-09-03 17:58:31</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:13:57.358073</p>
<p class='attribute'><strong>测试结果 : </strong> 共 247，通过 163，失败 84，通过率= 65.99%</p>

<p class='description'>WutongApiTestReport</p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 65.99% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 84 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 163 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 247 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='failClass warning'>
    <td>TestCases.test_api.Test_api</td>
    <td class="text-center">247</td>
    <td class="text-center">163</td>
    <td class="text-center">84</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',247)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='pt1_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_001__充值_102工行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_2' class='none'>
    <td class='failCase'><div class='testcase'>test_api_002__充值后续_102工行充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_2'>失败</button>
    <div id='div_ft1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_2'>失败</button>
    <div id='div_ft1_2' class="collapse in">
    <pre>
    
ft1_2: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_3' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_003__充值_102工行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_4' class='none'>
    <td class='failCase'><div class='testcase'>test_api_004__充值后续_102工行充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>失败</button>
    <div id='div_ft1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_4'>失败</button>
    <div id='div_ft1_4' class="collapse in">
    <pre>
    
ft1_4: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_5' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_005__充值_103农行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_6' class='none'>
    <td class='failCase'><div class='testcase'>test_api_006__充值后续_103农行充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_6'>失败</button>
    <div id='div_ft1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_6'>失败</button>
    <div id='div_ft1_6' class="collapse in">
    <pre>
    
ft1_6: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_7' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_007__充值_103农行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_8' class='none'>
    <td class='failCase'><div class='testcase'>test_api_008__充值后续_103农行充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_8'>失败</button>
    <div id='div_ft1_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_8'>失败</button>
    <div id='div_ft1_8' class="collapse in">
    <pre>
    
ft1_8: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_9' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_009__充值_104中行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_10' class='none'>
    <td class='failCase'><div class='testcase'>test_api_010__充值后续_104中行充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_10'>失败</button>
    <div id='div_ft1_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_10'>失败</button>
    <div id='div_ft1_10' class="collapse in">
    <pre>
    
ft1_10: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_11' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_011__充值_104中行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_12' class='none'>
    <td class='failCase'><div class='testcase'>test_api_012__充值后续_104中行充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_12' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_12'>失败</button>
    <div id='div_ft1_12' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_12' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_12'>失败</button>
    <div id='div_ft1_12' class="collapse in">
    <pre>
    
ft1_12: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_13' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_013__充值_105建行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_14' class='none'>
    <td class='failCase'><div class='testcase'>test_api_014__充值后续_105建行充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_14' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_14'>失败</button>
    <div id='div_ft1_14' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_14' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_14'>失败</button>
    <div id='div_ft1_14' class="collapse in">
    <pre>
    
ft1_14: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_15' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_015__充值_105建行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_16' class='none'>
    <td class='failCase'><div class='testcase'>test_api_016__充值后续_105建行充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_16' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_16'>失败</button>
    <div id='div_ft1_16' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_16' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_16'>失败</button>
    <div id='div_ft1_16' class="collapse in">
    <pre>
    
ft1_16: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_17' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_017__充值_301交通充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_18' class='none'>
    <td class='failCase'><div class='testcase'>test_api_018__充值后续_301交通充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_18' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_18'>失败</button>
    <div id='div_ft1_18' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_18' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_18'>失败</button>
    <div id='div_ft1_18' class="collapse in">
    <pre>
    
ft1_18: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_19' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_019__充值_301交通充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_20' class='none'>
    <td class='failCase'><div class='testcase'>test_api_020__充值后续_301交通充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_20' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_20'>失败</button>
    <div id='div_ft1_20' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_20' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_20'>失败</button>
    <div id='div_ft1_20' class="collapse in">
    <pre>
    
ft1_20: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_21' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_021__充值_302中信充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_22' class='none'>
    <td class='failCase'><div class='testcase'>test_api_022__充值后续_302中信充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_22' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_22'>失败</button>
    <div id='div_ft1_22' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_22' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_22'>失败</button>
    <div id='div_ft1_22' class="collapse in">
    <pre>
    
ft1_22: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_23' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_023__充值_302中信充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_24' class='none'>
    <td class='failCase'><div class='testcase'>test_api_024__充值后续_302中信充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_24' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_24'>失败</button>
    <div id='div_ft1_24' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_24' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_24'>失败</button>
    <div id='div_ft1_24' class="collapse in">
    <pre>
    
ft1_24: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_25' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_025__充值_303光大充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_26' class='none'>
    <td class='failCase'><div class='testcase'>test_api_026__充值后续_303光大充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_26' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_26'>失败</button>
    <div id='div_ft1_26' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_26' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_26'>失败</button>
    <div id='div_ft1_26' class="collapse in">
    <pre>
    
ft1_26: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_27' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_027__充值_303光大充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_28' class='none'>
    <td class='failCase'><div class='testcase'>test_api_028__充值后续_303光大充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_28' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_28'>失败</button>
    <div id='div_ft1_28' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_28' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_28'>失败</button>
    <div id='div_ft1_28' class="collapse in">
    <pre>
    
ft1_28: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_29' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_029__充值_304华夏充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_30' class='none'>
    <td class='failCase'><div class='testcase'>test_api_030__充值后续_304华夏充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_30' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_30'>失败</button>
    <div id='div_ft1_30' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_30' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_30'>失败</button>
    <div id='div_ft1_30' class="collapse in">
    <pre>
    
ft1_30: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_31' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_031__充值_304华夏充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_32' class='none'>
    <td class='failCase'><div class='testcase'>test_api_032__充值后续_304华夏充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_32' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_32'>失败</button>
    <div id='div_ft1_32' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_32' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_32'>失败</button>
    <div id='div_ft1_32' class="collapse in">
    <pre>
    
ft1_32: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_33' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_033__充值_305民生充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_34' class='none'>
    <td class='failCase'><div class='testcase'>test_api_034__充值后续_305民生充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_34' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_34'>失败</button>
    <div id='div_ft1_34' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_34' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_34'>失败</button>
    <div id='div_ft1_34' class="collapse in">
    <pre>
    
ft1_34: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_35' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_035__充值_305民生充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_36' class='none'>
    <td class='failCase'><div class='testcase'>test_api_036__充值后续_305民生充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_36' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_36'>失败</button>
    <div id='div_ft1_36' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_36' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_36'>失败</button>
    <div id='div_ft1_36' class="collapse in">
    <pre>
    
ft1_36: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_37' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_037__充值_306广发充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_38' class='none'>
    <td class='failCase'><div class='testcase'>test_api_038__充值后续_306工行充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_38' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_38'>失败</button>
    <div id='div_ft1_38' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_38' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_38'>失败</button>
    <div id='div_ft1_38' class="collapse in">
    <pre>
    
ft1_38: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_39' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_039__充值_306广发充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_40' class='none'>
    <td class='failCase'><div class='testcase'>test_api_040__充值后续_306工行充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_40' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_40'>失败</button>
    <div id='div_ft1_40' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_40' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_40'>失败</button>
    <div id='div_ft1_40' class="collapse in">
    <pre>
    
ft1_40: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_41' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_041__充值_307平安充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_42' class='none'>
    <td class='failCase'><div class='testcase'>test_api_042__充值后续_307平安充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_42' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_42'>失败</button>
    <div id='div_ft1_42' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_42' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_42'>失败</button>
    <div id='div_ft1_42' class="collapse in">
    <pre>
    
ft1_42: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_43' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_043__充值_307平安充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_44' class='none'>
    <td class='failCase'><div class='testcase'>test_api_044__充值后续_307平安充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_44' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_44'>失败</button>
    <div id='div_ft1_44' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_44' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_44'>失败</button>
    <div id='div_ft1_44' class="collapse in">
    <pre>
    
ft1_44: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_45' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_045__充值_308招商充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_46' class='none'>
    <td class='failCase'><div class='testcase'>test_api_046__充值后续_308招商充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_46' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_46'>失败</button>
    <div id='div_ft1_46' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_46' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_46'>失败</button>
    <div id='div_ft1_46' class="collapse in">
    <pre>
    
ft1_46: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_47' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_047__充值_308招商充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_48' class='none'>
    <td class='failCase'><div class='testcase'>test_api_048__充值后续_308招商充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_48' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_48'>失败</button>
    <div id='div_ft1_48' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_48' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_48'>失败</button>
    <div id='div_ft1_48' class="collapse in">
    <pre>
    
ft1_48: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_49' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_049__充值_309兴业充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_50' class='none'>
    <td class='failCase'><div class='testcase'>test_api_050__充值后续_309工行充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_50' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_50'>失败</button>
    <div id='div_ft1_50' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_50' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_50'>失败</button>
    <div id='div_ft1_50' class="collapse in">
    <pre>
    
ft1_50: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_51' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_051__充值_309兴业充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_52' class='none'>
    <td class='failCase'><div class='testcase'>test_api_052__充值后续_309工行充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_52' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_52'>失败</button>
    <div id='div_ft1_52' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_52' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_52'>失败</button>
    <div id='div_ft1_52' class="collapse in">
    <pre>
    
ft1_52: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_53' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_053__充值_310浦发充值成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_54' class='none'>
    <td class='failCase'><div class='testcase'>test_api_054__充值后续_310浦发充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_54' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_54'>失败</button>
    <div id='div_ft1_54' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_54' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_54'>失败</button>
    <div id='div_ft1_54' class="collapse in">
    <pre>
    
ft1_54: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_55' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_055__充值_310浦发充值成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_56' class='none'>
    <td class='failCase'><div class='testcase'>test_api_056__充值后续_310浦发充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_56' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_56'>失败</button>
    <div id='div_ft1_56' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_56' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_56'>失败</button>
    <div id='div_ft1_56' class="collapse in">
    <pre>
    
ft1_56: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_57' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_057__充值_403邮政充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_58' class='none'>
    <td class='failCase'><div class='testcase'>test_api_058__充值后续_403邮政充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_58' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_58'>失败</button>
    <div id='div_ft1_58' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_58' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_58'>失败</button>
    <div id='div_ft1_58' class="collapse in">
    <pre>
    
ft1_58: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_59' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_059__充值_403邮政充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_60' class='none'>
    <td class='failCase'><div class='testcase'>test_api_060__充值后续_403邮政充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_60' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_60'>失败</button>
    <div id='div_ft1_60' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_60' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_60'>失败</button>
    <div id='div_ft1_60' class="collapse in">
    <pre>
    
ft1_60: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_61' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_061__充值_810北京银行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_62' class='none'>
    <td class='failCase'><div class='testcase'>test_api_062__充值后续_810北京银行充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_62' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_62'>失败</button>
    <div id='div_ft1_62' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_62' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_62'>失败</button>
    <div id='div_ft1_62' class="collapse in">
    <pre>
    
ft1_62: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_63' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_063__充值_810北京银行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_64' class='none'>
    <td class='failCase'><div class='testcase'>test_api_064__充值后续_810北京银行充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_64' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_64'>失败</button>
    <div id='div_ft1_64' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_64' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_64'>失败</button>
    <div id='div_ft1_64' class="collapse in">
    <pre>
    
ft1_64: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_65' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_065__充值_811上海银行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_66' class='none'>
    <td class='failCase'><div class='testcase'>test_api_066__充值后续_811上海银行充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_66' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_66'>失败</button>
    <div id='div_ft1_66' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_66' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_66'>失败</button>
    <div id='div_ft1_66' class="collapse in">
    <pre>
    
ft1_66: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_67' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_067__充值_811上海银行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_68' class='none'>
    <td class='failCase'><div class='testcase'>test_api_068__充值后续_811上海银行充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_68' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_68'>失败</button>
    <div id='div_ft1_68' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_68' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_68'>失败</button>
    <div id='div_ft1_68' class="collapse in">
    <pre>
    
ft1_68: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_69' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_069__充值_813宁波银行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_70' class='none'>
    <td class='failCase'><div class='testcase'>test_api_070__充值后续_813宁波银行充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_70' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_70'>失败</button>
    <div id='div_ft1_70' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_70' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_70'>失败</button>
    <div id='div_ft1_70' class="collapse in">
    <pre>
    
ft1_70: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_71' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_071__充值_813宁波银行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_72' class='none'>
    <td class='failCase'><div class='testcase'>test_api_072__充值后续_813宁波银行充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_72' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_72'>失败</button>
    <div id='div_ft1_72' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_72' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_72'>失败</button>
    <div id='div_ft1_72' class="collapse in">
    <pre>
    
ft1_72: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_73' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_073__充值_973江苏银行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_74' class='none'>
    <td class='failCase'><div class='testcase'>test_api_074__充值后续_973江苏银行充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_74' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_74'>失败</button>
    <div id='div_ft1_74' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_74' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_74'>失败</button>
    <div id='div_ft1_74' class="collapse in">
    <pre>
    
ft1_74: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_75' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_075__充值_973江苏银行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_76' class='none'>
    <td class='failCase'><div class='testcase'>test_api_076__充值后续_973江苏银行充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_76' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_76'>失败</button>
    <div id='div_ft1_76' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_76' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_76'>失败</button>
    <div id='div_ft1_76' class="collapse in">
    <pre>
    
ft1_76: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_77' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_077__充值_970南京银行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_78' class='none'>
    <td class='failCase'><div class='testcase'>test_api_078__充值后续_970南京银行充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_78' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_78'>失败</button>
    <div id='div_ft1_78' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_78' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_78'>失败</button>
    <div id='div_ft1_78' class="collapse in">
    <pre>
    
ft1_78: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_79' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_079__充值_970南京银行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_80' class='none'>
    <td class='failCase'><div class='testcase'>test_api_080__充值后续_970南京银行充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_80' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_80'>失败</button>
    <div id='div_ft1_80' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_80' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_80'>失败</button>
    <div id='div_ft1_80' class="collapse in">
    <pre>
    
ft1_80: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_81' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_081__充值_974江西银行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_82' class='none'>
    <td class='failCase'><div class='testcase'>test_api_082__充值后续_974江西银行充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_82' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_82'>失败</button>
    <div id='div_ft1_82' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_82' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_82'>失败</button>
    <div id='div_ft1_82' class="collapse in">
    <pre>
    
ft1_82: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_83' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_083__充值_974江西银行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_84' class='none'>
    <td class='failCase'><div class='testcase'>test_api_084__充值后续_974江西银行充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_84' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_84'>失败</button>
    <div id='div_ft1_84' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_84' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_84'>失败</button>
    <div id='div_ft1_84' class="collapse in">
    <pre>
    
ft1_84: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_85' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_085__充值_315恒丰银行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_86' class='none'>
    <td class='failCase'><div class='testcase'>test_api_086__充值后续_315恒丰银行充值成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_86' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_86'>失败</button>
    <div id='div_ft1_86' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_86' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_86'>失败</button>
    <div id='div_ft1_86' class="collapse in">
    <pre>
    
ft1_86: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_87' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_087__充值_315恒丰银行充值</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_88' class='none'>
    <td class='failCase'><div class='testcase'>test_api_088__充值后续_315恒丰银行充值失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_88' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_88'>失败</button>
    <div id='div_ft1_88' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_88' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_88'>失败</button>
    <div id='div_ft1_88' class="collapse in">
    <pre>
    
ft1_88: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0001', 'tradeStatus': 'F', 'tradeMsg': '交易失败', 'errMsg': '交易失败', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_89' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_089__充值_充值金额含特殊符号</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_90' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_090__充值_cusno与其他参数不匹配</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_91' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_091__充值_cusno错误</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_92' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_092__提现_交易类型为952取现</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_93' class='none'>
    <td class='failCase'><div class='testcase'>test_api_093__提现后续_交易类型为952取现成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_93' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_93'>失败</button>
    <div id='div_ft1_93' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_93' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_93'>失败</button>
    <div id='div_ft1_93' class="collapse in">
    <pre>
    
ft1_93: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_94' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_094__提现_交易类型为952取现</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_95' class='none'>
    <td class='failCase'><div class='testcase'>test_api_095__提现后续_交易类型为952取现失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_95' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_95'>失败</button>
    <div id='div_ft1_95' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_95' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_95'>失败</button>
    <div id='div_ft1_95' class="collapse in">
    <pre>
    
ft1_95: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 71, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 67, in test_api
    self.assertIsNotNone(re.search(case_data["expected_data"],str(res)))
AssertionError: unexpectedly None


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_96' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_096__提现_提现金额含空格</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_97' class='none'>
    <td class='failCase'><div class='testcase'>test_api_097__提现_提现金额含特殊字符</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_97' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_97'>失败</button>
    <div id='div_ft1_97' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_97' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_97'>失败</button>
    <div id='div_ft1_97' class="collapse in">
    <pre>
    
ft1_97: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: 'ad.java:745)' not found in 'Failed to invoke method withdraw, cause: java.lang.NumberFormatException'


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_98' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_098__提现_提现金额_账户余额</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_99' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_099__提现_客户号不存在</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_100' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_100__提现_客户号与其他参数不匹配</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_101' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_101__提现_交易类型为924取现成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_102' class='none'>
    <td class='failCase'><div class='testcase'>test_api_102__提现后续_交易类型为924取现成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_102' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_102'>失败</button>
    <div id='div_ft1_102' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_102' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_102'>失败</button>
    <div id='div_ft1_102' class="collapse in">
    <pre>
    
ft1_102: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_103' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_103__提现_交易类型为924取现成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_104' class='none'>
    <td class='failCase'><div class='testcase'>test_api_104__提现后续_交易类型为924取现失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_104' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_104'>失败</button>
    <div id='div_ft1_104' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_104' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_104'>失败</button>
    <div id='div_ft1_104' class="collapse in">
    <pre>
    
ft1_104: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 71, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 67, in test_api
    self.assertIsNotNone(re.search(case_data["expected_data"],str(res)))
AssertionError: unexpectedly None


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_105' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_105__提现_交易类型错误</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_106' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_106__提现_渠道为2手机取现成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_107' class='none'>
    <td class='failCase'><div class='testcase'>test_api_107__提现后续_渠道accptmd为2手机取现成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_107' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_107'>失败</button>
    <div id='div_ft1_107' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_107' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_107'>失败</button>
    <div id='div_ft1_107' class="collapse in">
    <pre>
    
ft1_107: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_108' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_108__提现_渠道为2手机取现成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_109' class='none'>
    <td class='failCase'><div class='testcase'>test_api_109__提现后续_渠道accptmd为2手机取现失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_109' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_109'>失败</button>
    <div id='div_ft1_109' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_109' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_109'>失败</button>
    <div id='div_ft1_109' class="collapse in">
    <pre>
    
ft1_109: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 71, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 67, in test_api
    self.assertIsNotNone(re.search(case_data["expected_data"],str(res)))
AssertionError: unexpectedly None


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_110' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_110__提现_渠道为3企业版取现成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_111' class='none'>
    <td class='failCase'><div class='testcase'>test_api_111__提现后续_渠道accptmd为3企业版取现成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_111' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_111'>失败</button>
    <div id='div_ft1_111' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_111' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_111'>失败</button>
    <div id='div_ft1_111' class="collapse in">
    <pre>
    
ft1_111: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_112' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_112__提现_渠道accptmd为3企业版取现成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_113' class='none'>
    <td class='failCase'><div class='testcase'>test_api_113__提现后续_渠道accptmd为3企业版取现失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_113' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_113'>失败</button>
    <div id='div_ft1_113' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_113' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_113'>失败</button>
    <div id='div_ft1_113' class="collapse in">
    <pre>
    
ft1_113: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 71, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 67, in test_api
    self.assertIsNotNone(re.search(case_data["expected_data"],str(res)))
AssertionError: unexpectedly None


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_114' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_114__提现_即信路由代码为2取现成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_115' class='none'>
    <td class='failCase'><div class='testcase'>test_api_115__提现后续_即信路由代码routecode为2取现成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_115' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_115'>失败</button>
    <div id='div_ft1_115' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_115' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_115'>失败</button>
    <div id='div_ft1_115' class="collapse in">
    <pre>
    
ft1_115: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_116' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_116__提现_即信路由代码routecode为2取现成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_117' class='none'>
    <td class='failCase'><div class='testcase'>test_api_117__提现后续_即信路由代码routecode为2取现失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_117' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_117'>失败</button>
    <div id='div_ft1_117' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_117' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_117'>失败</button>
    <div id='div_ft1_117' class="collapse in">
    <pre>
    
ft1_117: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 71, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 67, in test_api
    self.assertIsNotNone(re.search(case_data["expected_data"],str(res)))
AssertionError: unexpectedly None


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_118' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_118__提现_支付模式错误</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_119' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_119__提现_return_url返回梧桐页面链接为空</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_120' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_120__提现_忘记密码链接为空</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_121' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_121__余额购买_购买随心投产品申请成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_122' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_122__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_123' class='none'>
    <td class='failCase'><div class='testcase'>test_api_123__余额购买_购买金额大于账户可用余额</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_123' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_123'>失败</button>
    <div id='div_ft1_123' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_123' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_123'>失败</button>
    <div id='div_ft1_123' class="collapse in">
    <pre>
    
ft1_123: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'F', 'tradeMsg': '查询不到唯一的关联持仓扩展编号！', 'errMsg': '申请成功', 'tradeCode': 'BC22', 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'F', 'tradeMsg': '产品余额不足或者账户余额不足！', 'errMsg': '申请成功', 'tradeCode': 'BC21', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_124' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_124__余额购买_购买金额大于产品剩余可购金额</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_125' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_125__余额购买_输入金额含空格</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_126' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_126__余额购买_输入金额含特殊字符</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_127' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_127__余额购买_购买系统加息随心投产品</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_128' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_128__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_129' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_129__余额购买_使用加息券购买随心投产品</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_130' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_130__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_131' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_131__余额购买_使用返现券购买随心投产品</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_132' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_132__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_133' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_133__余额购买_购买随意转产品</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_134' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_134__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_135' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_135__余额购买_购买月月盈产品</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_136' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_136__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_137' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_137__余额购买_购买季季升产品</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_138' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_138__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_139' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_139__余额购买_购买双季智选产品</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_140' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_140__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_141' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_141__余额购买_购买四季甄选产品</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_142' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_142__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_143' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_143__余额购买_cusno不存在</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_144' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_144__余额购买_productid不存在</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_145' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_145__余额购买_渠道2_手机购买随心投产品成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_146' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_146__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_147' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_147__余额购买_渠道3_企业版购买随心投产品成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_148' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_148__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_149' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_149__组合卖出_双季产品开放日卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_150' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_150__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_151' class='none'>
    <td class='failCase'><div class='testcase'>test_api_151__卖出后续接口_双季产品开放日卖出成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_151' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_151'>失败</button>
    <div id='div_ft1_151' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_151' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_151'>失败</button>
    <div id='div_ft1_151' class="collapse in">
    <pre>
    
ft1_151: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_152' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_152__组合卖出_双季产品开放日卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_153' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_153__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_154' class='none'>
    <td class='failCase'><div class='testcase'>test_api_154__卖出后续接口_双季产品开放日卖出失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_154' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_154'>失败</button>
    <div id='div_ft1_154' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_154' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_154'>失败</button>
    <div id='div_ft1_154' class="collapse in">
    <pre>
    
ft1_154: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 71, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 67, in test_api
    self.assertIsNotNone(re.search(case_data["expected_data"],str(res)))
AssertionError: unexpectedly None


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_155' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_155__组合卖出_双季产品提前卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_156' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_156__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_157' class='none'>
    <td class='failCase'><div class='testcase'>test_api_157__卖出后续接口_双季产品提前卖出成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_157' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_157'>失败</button>
    <div id='div_ft1_157' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_157' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_157'>失败</button>
    <div id='div_ft1_157' class="collapse in">
    <pre>
    
ft1_157: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_158' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_158__组合卖出_双季产品提前卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_159' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_159__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_160' class='none'>
    <td class='failCase'><div class='testcase'>test_api_160__卖出后续接口_双季产品开放日卖出失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_160' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_160'>失败</button>
    <div id='div_ft1_160' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_160' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_160'>失败</button>
    <div id='div_ft1_160' class="collapse in">
    <pre>
    
ft1_160: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 71, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 67, in test_api
    self.assertIsNotNone(re.search(case_data["expected_data"],str(res)))
AssertionError: unexpectedly None


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_161' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_161__组合卖出_双季产品不在开放日卖出</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_162' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_162__散标转让_散标转让申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_163' class='none'>
    <td class='failCase'><div class='testcase'>test_api_163__散标转让_散标转让购买申请</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_163' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_163'>失败</button>
    <div id='div_ft1_163' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_163' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_163'>失败</button>
    <div id='div_ft1_163' class="collapse in">
    <pre>
    
ft1_163: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'F', 'tradeMsg': '查询交易原单结果为空或失败', 'errMsg': '申请成功', 'tradeCode': 'Q015', 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_164' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_164__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_165' class='none'>
    <td class='failCase'><div class='testcase'>test_api_165__转让购买后续接口_散标转让购买成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_165' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_165'>失败</button>
    <div id='div_ft1_165' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_165' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_165'>失败</button>
    <div id='div_ft1_165' class="collapse in">
    <pre>
    
ft1_165: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_166' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_166__散标转让_散标转让申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_167' class='none'>
    <td class='failCase'><div class='testcase'>test_api_167__散标转让_散标转让购买申请</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_167' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_167'>失败</button>
    <div id='div_ft1_167' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_167' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_167'>失败</button>
    <div id='div_ft1_167' class="collapse in">
    <pre>
    
ft1_167: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'F', 'tradeMsg': '查询交易原单结果为空或失败', 'errMsg': '申请成功', 'tradeCode': 'Q015', 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_168' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_168__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_169' class='none'>
    <td class='failCase'><div class='testcase'>test_api_169__转让购买后续接口_散标转让购买失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_169' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_169'>失败</button>
    <div id='div_ft1_169' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_169' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_169'>失败</button>
    <div id='div_ft1_169' class="collapse in">
    <pre>
    
ft1_169: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'F', 'tradeMsg': '浜ゆ槗澶辫触', 'errMsg': '申请成功', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_170' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_170__散标转让_转让金额含空格</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_171' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_171__散标转让_转让金额含特殊字符</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_172' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_172__散标转让_转让份额大于购买份额购买失败</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_173' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_173__组合卖出_季季升产品提前卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_174' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_174__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_175' class='none'>
    <td class='failCase'><div class='testcase'>test_api_175__卖出后续接口_季季升产品提前卖出成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_175' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_175'>失败</button>
    <div id='div_ft1_175' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_175' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_175'>失败</button>
    <div id='div_ft1_175' class="collapse in">
    <pre>
    
ft1_175: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_176' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_176__组合卖出_季季升产品提前卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_177' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_177__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_178' class='none'>
    <td class='failCase'><div class='testcase'>test_api_178__卖出后续接口_季季升产品提前卖出失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_178' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_178'>失败</button>
    <div id='div_ft1_178' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_178' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_178'>失败</button>
    <div id='div_ft1_178' class="collapse in">
    <pre>
    
ft1_178: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'F', 'tradeMsg': '浜ゆ槗澶辫触', 'errMsg': '申请成功', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_179' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_179__组合卖出_使用优惠券季季升产品提前卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_180' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_180__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_181' class='none'>
    <td class='failCase'><div class='testcase'>test_api_181__卖出后续接口_使用优惠券季季升产品提前卖出成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_181' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_181'>失败</button>
    <div id='div_ft1_181' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_181' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_181'>失败</button>
    <div id='div_ft1_181' class="collapse in">
    <pre>
    
ft1_181: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_182' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_182__组合卖出_使用优惠券季季升产品提前卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_183' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_183__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_184' class='none'>
    <td class='failCase'><div class='testcase'>test_api_184__卖出后续接口_使用优惠券季季升产品提前卖出失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_184' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_184'>失败</button>
    <div id='div_ft1_184' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_184' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_184'>失败</button>
    <div id='div_ft1_184' class="collapse in">
    <pre>
    
ft1_184: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'F', 'tradeMsg': '浜ゆ槗澶辫触', 'errMsg': '申请成功', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_185' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_185__组合卖出_月月盈产品提前卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_186' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_186__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_187' class='none'>
    <td class='failCase'><div class='testcase'>test_api_187__卖出后续接口_月月盈产品提前卖出成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_187' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_187'>失败</button>
    <div id='div_ft1_187' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_187' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_187'>失败</button>
    <div id='div_ft1_187' class="collapse in">
    <pre>
    
ft1_187: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_188' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_188__组合卖出_月月盈产品提前卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_189' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_189__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_190' class='none'>
    <td class='failCase'><div class='testcase'>test_api_190__卖出后续接口_月月盈产品提前卖出失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_190' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_190'>失败</button>
    <div id='div_ft1_190' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_190' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_190'>失败</button>
    <div id='div_ft1_190' class="collapse in">
    <pre>
    
ft1_190: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'F', 'tradeMsg': '浜ゆ槗澶辫触', 'errMsg': '申请成功', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_191' class='none'>
    <td class='failCase'><div class='testcase'>test_api_191__组合卖出_使用优惠券季季升产品提前卖出申请</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_191' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_191'>失败</button>
    <div id='div_ft1_191' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_191' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_191'>失败</button>
    <div id='div_ft1_191' class="collapse in">
    <pre>
    
ft1_191: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'E', 'tradeMsg': '系统异常', 'errMsg': '申请成功', 'tradeCode': '9999', 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_192' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_192__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_193' class='none'>
    <td class='failCase'><div class='testcase'>test_api_193__卖出后续接口_使用优惠券月月盈产品提前卖出成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_193' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_193'>失败</button>
    <div id='div_ft1_193' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_193' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_193'>失败</button>
    <div id='div_ft1_193' class="collapse in">
    <pre>
    
ft1_193: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'BC44', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '更新锁状态异常', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_194' class='none'>
    <td class='failCase'><div class='testcase'>test_api_194__组合卖出_使用优惠券月月盈产品提前卖出申请</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_194' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_194'>失败</button>
    <div id='div_ft1_194' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_194' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_194'>失败</button>
    <div id='div_ft1_194' class="collapse in">
    <pre>
    
ft1_194: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'E', 'tradeMsg': '系统异常', 'errMsg': '申请成功', 'tradeCode': '9999', 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_195' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_195__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_196' class='none'>
    <td class='failCase'><div class='testcase'>test_api_196__卖出后续接口_使用优惠券月月盈产品提前卖出失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_196' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_196'>失败</button>
    <div id='div_ft1_196' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_196' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_196'>失败</button>
    <div id='div_ft1_196' class="collapse in">
    <pre>
    
ft1_196: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'BC44', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '更新锁状态异常', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'F', 'tradeMsg': '浜ゆ槗澶辫触', 'errMsg': '申请成功', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_197' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_197__组合卖出_四季甄选产品提前卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_198' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_198__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_199' class='none'>
    <td class='failCase'><div class='testcase'>test_api_199__卖出后续接口_四季甄选产品提前卖出成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_199' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_199'>失败</button>
    <div id='div_ft1_199' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_199' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_199'>失败</button>
    <div id='div_ft1_199' class="collapse in">
    <pre>
    
ft1_199: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_200' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_200__组合卖出_四季甄选产品提前卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_201' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_201__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_202' class='none'>
    <td class='failCase'><div class='testcase'>test_api_202__卖出后续接口_四季甄选产品提前卖出失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_202' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_202'>失败</button>
    <div id='div_ft1_202' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_202' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_202'>失败</button>
    <div id='div_ft1_202' class="collapse in">
    <pre>
    
ft1_202: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'F', 'tradeMsg': '浜ゆ槗澶辫触', 'errMsg': '申请成功', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_203' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_203__组合卖出_使用优惠券四季甄选产品提前卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_204' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_204__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_205' class='none'>
    <td class='failCase'><div class='testcase'>test_api_205__卖出后续接口_使用优惠券四季甄选产品提前卖出成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_205' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_205'>失败</button>
    <div id='div_ft1_205' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_205' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_205'>失败</button>
    <div id='div_ft1_205' class="collapse in">
    <pre>
    
ft1_205: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_206' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_206__组合卖出_使用优惠券四季甄选产品提前卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_207' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_207__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_208' class='none'>
    <td class='failCase'><div class='testcase'>test_api_208__卖出后续接口_使用优惠券四季甄选产品提前卖出失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_208' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_208'>失败</button>
    <div id='div_ft1_208' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_208' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_208'>失败</button>
    <div id='div_ft1_208' class="collapse in">
    <pre>
    
ft1_208: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'F', 'tradeMsg': '浜ゆ槗澶辫触', 'errMsg': '申请成功', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_209' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_209__组合卖出_月月盈产品开放日卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_210' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_210__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_211' class='none'>
    <td class='failCase'><div class='testcase'>test_api_211__卖出后续接口_月月盈产品开放日卖出成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_211' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_211'>失败</button>
    <div id='div_ft1_211' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_211' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_211'>失败</button>
    <div id='div_ft1_211' class="collapse in">
    <pre>
    
ft1_211: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_212' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_212__组合卖出_月月盈产品开放日卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_213' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_213__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_214' class='none'>
    <td class='failCase'><div class='testcase'>test_api_214__卖出后续接口_月月盈产品开放日卖出失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_214' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_214'>失败</button>
    <div id='div_ft1_214' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_214' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_214'>失败</button>
    <div id='div_ft1_214' class="collapse in">
    <pre>
    
ft1_214: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'F', 'tradeMsg': '浜ゆ槗澶辫触', 'errMsg': '申请成功', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_215' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_215__组合卖出_月月盈产品不在开放日卖出</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_216' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_216__组合卖出_季季升产品开放日卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_217' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_217__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_218' class='none'>
    <td class='failCase'><div class='testcase'>test_api_218__卖出后续接口_季季升产品开放日卖出成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_218' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_218'>失败</button>
    <div id='div_ft1_218' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_218' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_218'>失败</button>
    <div id='div_ft1_218' class="collapse in">
    <pre>
    
ft1_218: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_219' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_219__组合卖出_季季升产品开放日卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_220' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_220__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_221' class='none'>
    <td class='failCase'><div class='testcase'>test_api_221__卖出后续接口_季季升产品开放日卖出失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_221' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_221'>失败</button>
    <div id='div_ft1_221' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_221' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_221'>失败</button>
    <div id='div_ft1_221' class="collapse in">
    <pre>
    
ft1_221: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'F', 'tradeMsg': '浜ゆ槗澶辫触', 'errMsg': '申请成功', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_222' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_222__组合卖出_季季升产品不在开放日卖出</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_223' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_223__组合卖出_四季甄选产品开放日卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_224' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_224__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_225' class='none'>
    <td class='failCase'><div class='testcase'>test_api_225__卖出后续接口_四季甄选产品开放日卖出成功</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_225' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_225'>失败</button>
    <div id='div_ft1_225' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_225' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_225'>失败</button>
    <div id='div_ft1_225' class="collapse in">
    <pre>
    
ft1_225: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'Y', 'tradeMsg': '申请成功！', 'errMsg': '申请成功', 'tradeCode': '0000', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_226' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_226__组合卖出_四季甄选产品开放日卖出申请</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_227' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_227__调用轮询接口处理交易请求_</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='ft1_228' class='none'>
    <td class='failCase'><div class='testcase'>test_api_228__卖出后续接口_四季甄选产品开放日卖出失败</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_228' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_228'>失败</button>
    <div id='div_ft1_228' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_228' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_228'>失败</button>
    <div id='div_ft1_228' class="collapse in">
    <pre>
    
ft1_228: Traceback (most recent call last):
  File "F:\python36\lib\site-packages\ddt.py", line 150, in wrapper
    return func(self, *args, **kwargs)
  File "H:\python3_apiTest\TestCases\test_api.py", line 62, in test_api
    raise e
  File "H:\python3_apiTest\TestCases\test_api.py", line 58, in test_api
    self.assertIn(str(res),case_data["expected_data"])
AssertionError: "{'extFields': {}, 'errCode': 'Q015', 'tradeStatus': None, 'tradeMsg': None, 'errMsg': '查询交易原单结果为空或失败', 'tradeCode': None, 'exObjFields': {}, 'key': None}" not found in "{'extFields': {}, 'errCode': '0000', 'tradeStatus': 'F', 'tradeMsg': '浜ゆ槗澶辫触', 'errMsg': '申请成功', 'tradeCode': '0001', 'exObjFields': {}, 'key': None}"


    </pre>
    </div>
    </td>
</tr>

<tr id='pt1_229' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_229__组合卖出_四季甄选产品不在开放日卖出</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_230' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_230__账户注册_企业客户有推荐人成功注册</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_231' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_231__账户注册_个人客户无推荐人成功注册</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_232' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_232__账户注册_注册手机号为空</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_233' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_233__账户注册_登录密码为空</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_234' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_234__账户注册_注册手机号少于11位</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_235' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_235__账户注册_注册手机号大于11位</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_236' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_236__账户注册_注册手机号含特殊字符</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_237' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_237__账户注册_注册手机号含空格</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_238' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_238__账户注册_用户已注册</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_239' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_239__账户登录_账户官网登录成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_240' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_240__账户登录_账户柜台登录成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_241' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_241__账户登录_账户手机登录成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_242' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_242__账户登录_账户企业版登录成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_243' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_243__账户登录_账户微信登录成功</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_244' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_244__账户登录_用户名为空</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_245' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_245__账户登录_密码为空</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_246' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_246__账户登录_用户名错误</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='pt1_247' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_api_247__账户登录_密码错误</div></td>
    <td colspan='5' align='center'><span class="label label-success success">通过</span></td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>247</td>
    <td>163</td>
    <td>84</td>
    <td>0</td>
    <td>通过率：65.99%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
